baseURL = "http://yourdomain.com"
languageCode = "en-us"
title = "DSTA App Store"
theme = "mediumish"
summaryLength = 25
copyright = "Digital Hub - All rights reserved"
disqusShortname = "digitalDisque"
# googleAnalytics = ""
enableEmoji = true
pluralizelisttitles = false

[params]
  logo = "/images/chubbymonkey.png"
  description= "Welcome!"
  # mailchimp = ""

[params.author]
  name = "Digital Hub"
  thumbnail = "/images/chubbymonkey_author.png"
  description = "Digitalizing the way we defend"

## Landing Page

# [params.index]
#   picture = "/images/chubbymonkey.jpg"
#   title = "Digital Hub"
#   subtitle = "I'm a unique placeholder. Working here and there!"
#   mdtext = '''Currently trying to get this blog running, still don't know what the blog will be about!\
# '''
#   alertbar = true

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"

## Main Menu
[[menu.main]]
  name = "Home"
  weight = 100
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Computer Vision"
  weight = 200
  identifier = "Computer Vision"
  url = "/computer vision"

[[menu.main]]
  name = "Natural Language Processing"
  weight = 201
  identifier = "Natural Language Processing"
  url = "/natural language processing"

[[menu.main]]
  name = "Reinforcement Learning"
  weight = 202
  identifier = "Reinforcement Learning"
  url = "/reinforcement learning"

[[menu.main]]
  name = "Data Analytics"
  weight = 203
  identifier = "Data Analytics"
  url = "/data analytics"

# [[menu.main]]
#   name = "Home"
#   weight = 100
#   identifier = "home"
#   url = "/"

[[menu.main]]
  name = "News"
  identifier = "news"
  weight = 300
  url = "/static/news"

[[menu.main]]
  name = "Knowledge Graph"
  identifier = "knowledgeGraph"
  weight = 400
  url = "/static/knowledgeGraph"