baseURL = "http://yourdomain.com"
languageCode = "en-us"
title = "DH App Store"
theme = "mediumish"
summaryLength = 25
copyright = "Digital Hub - All rights reserved"
disqusShortname = "digitalDisque"
# googleAnalytics = ""
enableEmoji = true

[params]
  logo = "/images/chubbymonkey.png"
  description= "Welcome to DH app store!"
  # mailchimp = ""

[params.author]
  name = "Digital Hub"
  thumbnail = "/images/chubbymonkey_author.png"
  description = "Digitalizing the way we defend"

## Landing Page
[params.index]
  picture = "/images/chubbymonkey_author.png"
  title = "Digital Hub"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''Currently trying to get this blog running, still don't know what the blog will be about!\
'''
  alertbar = true

[params.social]
  github = "DinoHub"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "eujazzcity"

## Main Menu
[[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog"
[[menu.main]]
  name = "Home"
  weight = 100
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "News"
  identifier = "news"
  weight = 200
  url = "/static/news"

[[menu.main]]
  name = "Knowledge Graph"
  identifier = "knowledgeGraph"
  weight = 300
  url = "/static/knowledgeGraph"